[Proxy Group]
cfauto = fallback,CFAUTO,use=true,interval=600,timeout=5,url=http://www.gstatic.com/generate_204
cfus = fallback,CFUS,use=true,interval=600,timeout=5,url=http://www.gstatic.com/generate_204
pqjc = fallback,PQJC,use=true,interval=600,timeout=5,url=http://www.gstatic.com/generate_204,policy-regex-filter=美国.*-0.*1

[Rule]
DOMAIN-SUFFIX,dcard.tw,PQJC
