#!name=Whitlist
#!desc=PersonWhitlist Publisher:Person
# Shadowrocket


[Rule]
#———————————直连模块———————————
#Eastmoney
DOMAIN-SUFFIX,eastmoney.com,DIRECT

#Ths
DOMAIN-SUFFIX,10jqka.com.cn,DIRECT

#Apple
DOMAIN-SUFFIX,apple.com,DIRECT
DOMAIN-SUFFIX,apple.com.cn,DIRECT
DOMAIN-SUFFIX,icloud.com,DIRECT
DOMAIN-SUFFIX,icloud.com.cn,DIRECT
DOMAIN-SUFFIX,cdn-apple.com,DIRECT

#OKX
DOMAIN-SUFFIX,okx.com,DIRECT

#Block100
DOMAIN-SUFFIX,anythinktech.com,DIRECT

#Todesk
DOMAIN,todesk.com,DIRECT

#临时
DOMAIN-SUFFIX,centurygame.com,DIRECT
DOMAIN-SUFFIX,centurygames.net,DIRECT
DOMAIN-SUFFIX,hmma.baidu.com,DIRECT
DOMAIN-SUFFIX,hm.baidu.com,DIRECT
DOMAIN-SUFFIX,ilivedata.com,DIRECT
DOMAIN-SUFFIX,mtyy.tv,DIRECT
DOMAIN-SUFFIX,mtyy2.com,DIRECT

#———————————代理模块———————————
#Github
DOMAIN-SUFFIX,github.com,PROXY
DOMAIN-SUFFIX,githubusercontent.com,PROXY


#临时
DOMAIN-SUFFIX,mafiana.app,PROXY
DOMAIN-SUFFIX,munqu.com,PROXY
